version: "3.9"
services:
  urbanterror:
    image: leandrosalvas/urbanterror
    volumes: 
      - ./config/mapcycle.txt:/home/urt/urbanterror43/q3ut4/mapcycle.txt
      - ./config/server.cfg:/home/urt/urbanterror43/q3ut4/server.cfg
      - ./logs/games.log:/home/urt/urbanterror43/q3ut4/games.log
    ports:
      - "27960:27960/udp"
